In [1]:
import numpy as np

# Arrays

In [2]:
# Vamos a crear un array
primer_array = np.array([5,3,2,1,4])

In [3]:
# Vamos a imprimir el array que acabamos de crear
print(primer_array)

[5 3 2 1 4]


In [4]:
# Verificamos el tipo de dato de los elementos del array
primer_array.dtype

dtype('int64')

In [5]:
# Verificamos el tipo de dato de primer_array
type(primer_array)

numpy.ndarray

In [6]:
# Verifiquemos las dimensiones del array
primer_array.shape

(5,)

## Existen varias funciones para inicializar arrays

In [7]:
# Inicializar el array con 0, en base a una dimensión determinada
a_zeros = np.zeros([3])
a_zeros

array([0., 0., 0.])

In [8]:
# Inicializar el array con 1, en base a una dimensión determinada
a_ones = np.ones([9])
a_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Combinar arrays

In [9]:
array_1 = np.array([7,8,9])
array_2 = np.array([1,2,4])

In [10]:
print(array_1)
print(array_2)

[7 8 9]
[1 2 4]


In [11]:
# Vamos a combinarlos Verticalmente
array_v = np.vstack((array_1, array_2))
print(array_v.shape)
array_v

(2, 3)


array([[7, 8, 9],
       [1, 2, 4]])

In [12]:
# Vamos a combinarlos Horizontalmentee
array_h = np.hstack((array_1, array_2))
print(array_h.shape)
array_h

(6,)


array([7, 8, 9, 1, 2, 4])

## Arrays de 2 dimensiones

In [13]:
# Arrays de 2 dimensiones
dataset = np.array([[1,2],[5,6]])
print(dataset)

[[1 2]
 [5 6]]


In [14]:
type(dataset)

numpy.ndarray

## Indexing

In [15]:
## Acceder a los elementos de un array
a1 = np.array([3,4,5,1,2,4,12,22])
a1

array([ 3,  4,  5,  1,  2,  4, 12, 22])

In [16]:
# El index del primer elemento es 0
print(a1[0])

3


In [17]:
print(a1[6])

12


In [18]:
# En arrays de dos dimensiones
a2 = np.array([[5,3,1],[3,4,6]])
a2

array([[5, 3, 1],
       [3, 4, 6]])

In [19]:
# Acceder a un elemento en particular
a2[1,2]

6

In [20]:
# Acceder a toda una fila
a2[1,]

array([3, 4, 6])

In [21]:
# Acceder a toda una columna
a2[:,1]

array([3, 4])

## Slicing

In [22]:
# Dividir los datasets en X y y
datos = np.array([[0.23, 2, 0.34, 4, 1],
         [0.33, 3.4, 0.24, 3.2, 2],
         [0.43, 2.7, 0.14, 2.5, 1]])
datos


array([[0.23, 2.  , 0.34, 4.  , 1.  ],
       [0.33, 3.4 , 0.24, 3.2 , 2.  ],
       [0.43, 2.7 , 0.14, 2.5 , 1.  ]])

In [23]:
X, y = datos[:, :-1], datos[:,-1]

In [24]:
print(X)


[[0.23 2.   0.34 4.  ]
 [0.33 3.4  0.24 3.2 ]
 [0.43 2.7  0.14 2.5 ]]


In [25]:
print(y)

[1. 2. 1.]
