In [1]:
import numpy as np

# Operaciones con Vectores y Matrices

In [2]:
a1 = np.array([3,5,6])
a2 = np.array([6,3,1])

In [3]:
print (a1)
print ("----------")
print (a2)

[3 5 6]
----------
[6 3 1]


In [4]:
print (a1)
print ("+")
print (a2)
print ("========")
a1 + a2

[3 5 6]
+
[6 3 1]


array([9, 8, 7])

In [5]:
# Resta 
print (a1)
print ("-")
print (a2)
print ("========")
a1 - a2

[3 5 6]
-
[6 3 1]


array([-3,  2,  5])

In [6]:
# Multiplicación
print (a1)
print ("*")
print (a2)
print ("========")
a1 * a2

[3 5 6]
*
[6 3 1]


array([18, 15,  6])

In [7]:
# División
print (a1)
print ("/")
print (a2)
print ("========")
a1 / a2

[3 5 6]
/
[6 3 1]


array([0.5       , 1.66666667, 6.        ])

# Broadcasting

In [8]:
print(a1.shape)
a1

(3,)


array([3, 5, 6])

In [9]:
b = 5
b

5

In [ ]:
# a1 + b
# El escalar , será internamente replicado por numpy hasta alcanzar el tamaño de a1
# b quedará como b=[ 5, 5, 5]

In [10]:
print(a1)
print("+")
print(b)
print ("========")
a1 + b

[3 5 6]
+
5


array([ 8, 10, 11])

In [11]:
print(a1)
print("*")
print(b)
print ("========")
a1 * b

[3 5 6]
*
5


array([15, 25, 30])

In [12]:
a3 = np.array([[3,5,6], [8,3,2],[3,4,9]])
a3

array([[3, 5, 6],
       [8, 3, 2],
       [3, 4, 9]])

In [13]:
b2 = 3

In [ ]:
# a3 + b2
# El escalar debe alcanzar las dimensiones del array de 2 dimensiones
#    [[3, 3, 3],
#    [3, 3, 3],
#    [3, 3, 3]]

In [14]:
a3 + b2

array([[ 6,  8,  9],
       [11,  6,  5],
       [ 6,  7, 12]])

In [15]:
a3

array([[3, 5, 6],
       [8, 3, 2],
       [3, 4, 9]])

In [17]:
a1

array([3, 5, 6])

In [18]:
a3 + a1

array([[ 6, 10, 12],
       [11,  8,  8],
       [ 6,  9, 15]])

In [ ]:
# Broadcasting solo puede realizarse si las últimas dimensiones del array son iguales ó al menos una de las dimensiones es igual a 1