In [1]:
import numpy as np

# Tipos de matrices y sus operaciones

## Matriz cuadrada

In [2]:
# El número de filas es igual al número de columnas

A = np.array([[2,4],[3,4]])
A

array([[2, 4],
       [3, 4]])

In [3]:
# Dimensiones de la matriz
print(A.shape)

(2, 2)


## Matriz simétrica

In [4]:
# Es una matriz cuadrada donde la triangular superior es igual a la triangular inferior de la matriz
S = np.array([[5, 6, 7], [6, 3, 2], [7, 2, 1]])
S

array([[5, 6, 7],
       [6, 3, 2],
       [7, 2, 1]])

In [5]:
# Es una matriz simétrica cuando la matriz es igual a su traspuesta
print(S.T)

S == S.T

[[5 6 7]
 [6 3 2]
 [7 2 1]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Traspuesta de una matriz [Operación]

In [6]:
# Basicamente consiste en intercambiar los valores de las filas por los valores de las columnas
TR = np.array([
   [1, 2, 9],
   [3, 4, 8],
   [5, 6, 7]
])
print("Matriz Original")
print(TR)
print("---------------")
print ("Traspuesta de la matriz")
TR.T

Matriz Original
[[1 2 9]
 [3 4 8]
 [5 6 7]]
---------------
Transpuesta de la matriz


array([[1, 3, 5],
       [2, 4, 6],
       [9, 8, 7]])

In [7]:
# Veamos la matriz traspuesta en una matriz rectangular
TR2 = np.array([
   [1, 0, 9],
   [3, 4, 8]
])
print("Matriz Original")
print(TR2)
print("---------------")
print ("Traspuesta de la matriz")
TR2.T

Matriz Original
[[1 0 9]
 [3 4 8]]
---------------
Transpuesta de la matriz


array([[1, 3],
       [0, 4],
       [9, 8]])

## Matriz triangular

In [8]:
# Es una matriz cuadrada que tiene valores de 0 por encima o debajo de la diagonal principal 
# Triangular inferior
TRI =  np.array([
   [1, 2, 9, 22],
   [3, 4, 8, 32],
   [5, 6, 7, 42],
   [9, 2, 3, 62]
])
print("Matriz Original")
print(TRI)
print("----------------------------")
print("Matriz Triangular inferior")
TRI_INFERIOR = np.tril(TRI)
print(TRI_INFERIOR)
print("----------------------------")
print("Matriz Triangular Superior")
TRI_SUPERIOR = np.triu(TRI)
print(TRI_SUPERIOR)

Matriz Original
[[ 1  2  9 22]
 [ 3  4  8 32]
 [ 5  6  7 42]
 [ 9  2  3 62]]
----------------------------
Matriz Triangular inferior
[[ 1  0  0  0]
 [ 3  4  0  0]
 [ 5  6  7  0]
 [ 9  2  3 62]]
----------------------------
Matriz Triangular Superior
[[ 1  2  9 22]
 [ 0  4  8 32]
 [ 0  0  7 42]
 [ 0  0  0 62]]


## Matriz Diagonal

In [9]:
# En una Matriz Diagonal, todos los elementos fuera de la diagonal principal tienen el valor de 0
np.diag(TRI)

array([ 1,  4,  7, 62])

In [10]:
# Para obtener la diagonal de una matriz, no es necesario que la misma sea cuadrada
print(TR2)
np.diag(TR2)

[[1 0 9]
 [3 4 8]]


array([1, 4])

## Matriz Identidad

In [11]:
# Es la matriz que tiene 1 en la diagonal principal y ceros en el resto de sus elementos
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matriz inversa [Operación]

In [12]:
# Es aquella matriz que multiplicada por la matriz de origen da como resultado la matriz identidad
#     A . (A ^(-1)) = I
A = np.array([[-1, 1], [-2, 3]])
print(A)
print("-----------------")
# Calculamos la inversa de la matriz
A_inv = np.linalg.inv(A)
print(A_inv)
print("-----------------")
# Verificamos la condicion
I = A.dot(A_inv)
print(I)

[[-1  1]
 [-2  3]]
-----------------
[[-3.  1.]
 [-2.  1.]]
-----------------
[[1. 0.]
 [0. 1.]]


In [13]:
# Ahora definamos otra matriz y calculemos su inversa
A = np.array([[1, 2], [3, 4]])
print(A)
print("-----------------")
# Calculamos la inversa de la matriz
A_inv = np.linalg.inv(A)
print(A_inv)
print("-----------------")
# Verificamos la condicion
I = A.dot(A_inv)
print(I)


[[1 2]
 [3 4]]
-----------------
[[-2.   1. ]
 [ 1.5 -0.5]]
-----------------
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## Matriz Singular

In [14]:
# No todas las matrices son invertibles. (Matrices Singulares)

## Traza de una matriz  [Operación]

In [15]:
# Es la sumatoria de los elementos de la diagonal principal de la matriz
print(TRI)

[[ 1  2  9 22]
 [ 3  4  8 32]
 [ 5  6  7 42]
 [ 9  2  3 62]]


In [16]:
np.trace(TRI)

74

## Matriz Dispersa (Sparse Matrix)

In [17]:
# Son matrices donde la mayor cantidad de elementos son 0

In [18]:
A = np.array([
    [2, 0, 0, 0, 0, 0, 9, 0],
    [0, 1, 0, 0, 0, 0, 0, 2],
    [0, 0, 0, 0, 2, 0, 0, 0],
    [8, 0, 0, 0, 0, 0, 0, 0]
])

In [19]:
# sparsity = conteo_de_elementos_zero/ total_elementos
sparsity = 1 - np.count_nonzero(A) / (A.size)

In [20]:
sparsity

0.8125

In [21]:
from scipy.sparse import csr_matrix

In [22]:
# Salvar espacio
# Compressed Sparse Row
A_crow = csr_matrix(A)
print(A_crow)

  (0, 0)	2
  (0, 6)	9
  (1, 1)	1
  (1, 7)	2
  (2, 4)	2
  (3, 0)	8


In [23]:
# Reconstruimos la matriz
A_crow.todense()

matrix([[2, 0, 0, 0, 0, 0, 9, 0],
        [0, 1, 0, 0, 0, 0, 0, 2],
        [0, 0, 0, 0, 2, 0, 0, 0],
        [8, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

# Tensores

In [24]:
TEN1 = np.array([
    [
        [2,3,1], 
        [4,2,4],
        [5,2,4]
    ],
    [
        [12,89,122], 
        [33,23,33],
        [22,44,311]
    ],
    [
        [2,1,233], 
        [33,66,33],
        [74,32,33]
    ],
])

In [25]:
TEN1

array([[[  2,   3,   1],
        [  4,   2,   4],
        [  5,   2,   4]],

       [[ 12,  89, 122],
        [ 33,  23,  33],
        [ 22,  44, 311]],

       [[  2,   1, 233],
        [ 33,  66,  33],
        [ 74,  32,  33]]])

In [26]:
TEN1.shape

(3, 3, 3)