In [1]:
import numpy as np

# Descomposición de matrices

La descomposion de matrices, es util para reducir las matrices en elementos más sencillos que simplifiquen las operaciones complejas.


## Eigen decomposition

##### Valores propios - Eigen values
##### Vectores propios - Eigen vectors


Eigen decomposition descompone la matriz en eigen vectors y en eigen values, tal que

                                                                              
$ Av = \lambda v $


Donde: 

$ v $ el el eigen vector  , $ v \neq 0 $

$ \lambda $ es el eigen value

                                                                         

In [2]:
A = np.array([[1, 2, 0], [0, 3, 0], [2, -4,2]] )
A

array([[ 1,  2,  0],
       [ 0,  3,  0],
       [ 2, -4,  2]])

In [3]:
# Vamos a obtener los eigen vectors y eigen values de la matriz A
eigen_values, eigen_vectors = np.linalg.eig(A)

In [4]:
print("Eigen Value")
print(eigen_values)
print("---------------")
print("Eigen Vector")
print(eigen_vectors)

Eigen Value
[2. 1. 3.]
---------------
Eigen Vector
[[ 0.          0.4472136   0.40824829]
 [ 0.          0.          0.40824829]
 [ 1.         -0.89442719 -0.81649658]]


# Reconstrucción de la matriz A 

A partir de sus Eigen Values y de sus Eigen Vectors

$ A = Q \Lambda Q^{-1} $

Donde:

$ Q $ es la matriz de eigenvectors

$ \Lambda $ es la matriz diagonal de eigenvalues

In [5]:
# Creamos Q - Matriz de EigenVectors
Q = eigen_vectors

In [6]:
# Creamos la matriz diagonal de los eigenvalues
L_matrix = np.diag(eigen_values) 

In [7]:
# Creamos la inversa de Q
Q_inv = np.linalg.inv(Q)

In [8]:
# Reconstruimos la matriz original
A_reconstruida = Q.dot(L_matrix).dot(Q_inv)
A_reconstruida

array([[ 1.,  2.,  0.],
       [ 0.,  3.,  0.],
       [ 2., -4.,  2.]])

In [9]:
# La matriz original era: 
A

array([[ 1,  2,  0],
       [ 0,  3,  0],
       [ 2, -4,  2]])

In [10]:
# No todas las matrices pueden descomponerse en Eigen Values y Eigen Vectors